p = set()
s = input("Enter number:" )
p.add(int(s))
s = input("Enter number:" )
p.add(int(s))
s = input("Enter number:" )
p.add(int(s))
s = input("Enter number:" )
p.add(int(s))
s = input("Enter number:" )
p.add(int(s))
s = input("Enter number:" )
p.add(int(s))
s = input("Enter number:" )
p.add(int(s))
s = input("Enter number:" )
p.add(int(s))

print(p)